// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmf4bQ8xtyaEZrhh80enUNBCK4KcVbga0',
    appId: '1:594392570074:web:ecf36a153570dc8b026de3',
    messagingSenderId: '594392570074',
    projectId: 'untitled01-8741e',
    authDomain: 'untitled01-8741e.firebaseapp.com',
    storageBucket: 'untitled01-8741e.firebasestorage.app',
    measurementId: 'G-953EMQQFN8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQfBdsxMzvfA6trxUvu3zzYUDarnwmgj8',
    appId: '1:594392570074:android:34730049be372321026de3',
    messagingSenderId: '594392570074',
    projectId: 'untitled01-8741e',
    storageBucket: 'untitled01-8741e.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYE5z1YEpX0saB37tCt0mV1dnH9v7tWzc',
    appId: '1:594392570074:ios:6ae2003b6453b31f026de3',
    messagingSenderId: '594392570074',
    projectId: 'untitled01-8741e',
    storageBucket: 'untitled01-8741e.firebasestorage.app',
    iosBundleId: 'com.example.untitled1',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYE5z1YEpX0saB37tCt0mV1dnH9v7tWzc',
    appId: '1:594392570074:ios:6ae2003b6453b31f026de3',
    messagingSenderId: '594392570074',
    projectId: 'untitled01-8741e',
    storageBucket: 'untitled01-8741e.firebasestorage.app',
    iosBundleId: 'com.example.untitled1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmf4bQ8xtyaEZrhh80enUNBCK4KcVbga0',
    appId: '1:594392570074:web:7b28617c2a4276dd026de3',
    messagingSenderId: '594392570074',
    projectId: 'untitled01-8741e',
    authDomain: 'untitled01-8741e.firebaseapp.com',
    storageBucket: 'untitled01-8741e.firebasestorage.app',
    measurementId: 'G-LVR7YZ8ZTG',
  );
}
